/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package offrestage.model.impl;

import offrestage.model.Offrestage;

import offrestage.service.OffrestageLocalServiceUtil;

/**
 * The extended model base implementation for the Offrestage service. Represents a row in the &quot;WAFABAIL_Offrestage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OffrestageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OffrestageImpl
 * @see Offrestage
 * @generated
 */
public abstract class OffrestageBaseImpl
	extends OffrestageModelImpl implements Offrestage {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a offrestage model instance should use the <code>Offrestage</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			OffrestageLocalServiceUtil.addOffrestage(this);
		}
		else {
			OffrestageLocalServiceUtil.updateOffrestage(this);
		}
	}

}