/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package article.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Article service. Represents a row in the &quot;WAFABAIL_Article&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>article.model.impl.ArticleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>article.model.impl.ArticleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Article
 * @generated
 */
@ProviderType
public interface ArticleModel extends BaseModel<Article> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a article model instance should use the {@link Article} interface instead.
	 */

	/**
	 * Returns the primary key of this article.
	 *
	 * @return the primary key of this article
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this article.
	 *
	 * @param primaryKey the primary key of this article
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this article.
	 *
	 * @return the uuid of this article
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this article.
	 *
	 * @param uuid the uuid of this article
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the article ID of this article.
	 *
	 * @return the article ID of this article
	 */
	public long getArticleId();

	/**
	 * Sets the article ID of this article.
	 *
	 * @param articleId the article ID of this article
	 */
	public void setArticleId(long articleId);

	/**
	 * Returns the titre of this article.
	 *
	 * @return the titre of this article
	 */
	@AutoEscape
	public String getTitre();

	/**
	 * Sets the titre of this article.
	 *
	 * @param titre the titre of this article
	 */
	public void setTitre(String titre);

	/**
	 * Returns the detail of this article.
	 *
	 * @return the detail of this article
	 */
	@AutoEscape
	public String getDetail();

	/**
	 * Sets the detail of this article.
	 *
	 * @param detail the detail of this article
	 */
	public void setDetail(String detail);

	/**
	 * Returns the date creation of this article.
	 *
	 * @return the date creation of this article
	 */
	public Date getDateCreation();

	/**
	 * Sets the date creation of this article.
	 *
	 * @param dateCreation the date creation of this article
	 */
	public void setDateCreation(Date dateCreation);

	@Override
	public Article cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}