/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package offreemploi.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Offreemploi service. Represents a row in the &quot;WAFABAIL_Offreemploi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>offreemploi.model.impl.OffreemploiModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>offreemploi.model.impl.OffreemploiImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Offreemploi
 * @generated
 */
@ProviderType
public interface OffreemploiModel extends BaseModel<Offreemploi> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a offreemploi model instance should use the {@link Offreemploi} interface instead.
	 */

	/**
	 * Returns the primary key of this offreemploi.
	 *
	 * @return the primary key of this offreemploi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this offreemploi.
	 *
	 * @param primaryKey the primary key of this offreemploi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this offreemploi.
	 *
	 * @return the uuid of this offreemploi
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this offreemploi.
	 *
	 * @param uuid the uuid of this offreemploi
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the offreemploi ID of this offreemploi.
	 *
	 * @return the offreemploi ID of this offreemploi
	 */
	public long getOffreemploiId();

	/**
	 * Sets the offreemploi ID of this offreemploi.
	 *
	 * @param OffreemploiId the offreemploi ID of this offreemploi
	 */
	public void setOffreemploiId(long OffreemploiId);

	/**
	 * Returns the titre of this offreemploi.
	 *
	 * @return the titre of this offreemploi
	 */
	@AutoEscape
	public String getTitre();

	/**
	 * Sets the titre of this offreemploi.
	 *
	 * @param titre the titre of this offreemploi
	 */
	public void setTitre(String titre);

	/**
	 * Returns the detail of this offreemploi.
	 *
	 * @return the detail of this offreemploi
	 */
	@AutoEscape
	public String getDetail();

	/**
	 * Sets the detail of this offreemploi.
	 *
	 * @param detail the detail of this offreemploi
	 */
	public void setDetail(String detail);

	/**
	 * Returns the date creation of this offreemploi.
	 *
	 * @return the date creation of this offreemploi
	 */
	public Date getDateCreation();

	/**
	 * Sets the date creation of this offreemploi.
	 *
	 * @param dateCreation the date creation of this offreemploi
	 */
	public void setDateCreation(Date dateCreation);

	@Override
	public Offreemploi cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}