/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package offrestage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Offrestage service. Represents a row in the &quot;WAFABAIL_Offrestage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>offrestage.model.impl.OffrestageModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>offrestage.model.impl.OffrestageImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Offrestage
 * @generated
 */
@ProviderType
public interface OffrestageModel extends BaseModel<Offrestage> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a offrestage model instance should use the {@link Offrestage} interface instead.
	 */

	/**
	 * Returns the primary key of this offrestage.
	 *
	 * @return the primary key of this offrestage
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this offrestage.
	 *
	 * @param primaryKey the primary key of this offrestage
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this offrestage.
	 *
	 * @return the uuid of this offrestage
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this offrestage.
	 *
	 * @param uuid the uuid of this offrestage
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the stage ID of this offrestage.
	 *
	 * @return the stage ID of this offrestage
	 */
	public long getStageId();

	/**
	 * Sets the stage ID of this offrestage.
	 *
	 * @param stageId the stage ID of this offrestage
	 */
	public void setStageId(long stageId);

	/**
	 * Returns the titre of this offrestage.
	 *
	 * @return the titre of this offrestage
	 */
	@AutoEscape
	public String getTitre();

	/**
	 * Sets the titre of this offrestage.
	 *
	 * @param titre the titre of this offrestage
	 */
	public void setTitre(String titre);

	/**
	 * Returns the detail of this offrestage.
	 *
	 * @return the detail of this offrestage
	 */
	@AutoEscape
	public String getDetail();

	/**
	 * Sets the detail of this offrestage.
	 *
	 * @param detail the detail of this offrestage
	 */
	public void setDetail(String detail);

	/**
	 * Returns the date creation of this offrestage.
	 *
	 * @return the date creation of this offrestage
	 */
	public Date getDateCreation();

	/**
	 * Sets the date creation of this offrestage.
	 *
	 * @param dateCreation the date creation of this offrestage
	 */
	public void setDateCreation(Date dateCreation);

	@Override
	public Offrestage cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}