/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package revue.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Revue service. Represents a row in the &quot;WAFABAIL_Revue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>revue.model.impl.RevueModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>revue.model.impl.RevueImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Revue
 * @generated
 */
@ProviderType
public interface RevueModel extends BaseModel<Revue> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a revue model instance should use the {@link Revue} interface instead.
	 */

	/**
	 * Returns the primary key of this revue.
	 *
	 * @return the primary key of this revue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this revue.
	 *
	 * @param primaryKey the primary key of this revue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this revue.
	 *
	 * @return the uuid of this revue
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this revue.
	 *
	 * @param uuid the uuid of this revue
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the revue ID of this revue.
	 *
	 * @return the revue ID of this revue
	 */
	public long getRevueId();

	/**
	 * Sets the revue ID of this revue.
	 *
	 * @param revueId the revue ID of this revue
	 */
	public void setRevueId(long revueId);

	/**
	 * Returns the titre of this revue.
	 *
	 * @return the titre of this revue
	 */
	@AutoEscape
	public String getTitre();

	/**
	 * Sets the titre of this revue.
	 *
	 * @param titre the titre of this revue
	 */
	public void setTitre(String titre);

	/**
	 * Returns the details of this revue.
	 *
	 * @return the details of this revue
	 */
	@AutoEscape
	public String getDetails();

	/**
	 * Sets the details of this revue.
	 *
	 * @param details the details of this revue
	 */
	public void setDetails(String details);

	/**
	 * Returns the lien of this revue.
	 *
	 * @return the lien of this revue
	 */
	@AutoEscape
	public String getLien();

	/**
	 * Sets the lien of this revue.
	 *
	 * @param lien the lien of this revue
	 */
	public void setLien(String lien);

	/**
	 * Returns the date creation of this revue.
	 *
	 * @return the date creation of this revue
	 */
	public Date getDateCreation();

	/**
	 * Sets the date creation of this revue.
	 *
	 * @param dateCreation the date creation of this revue
	 */
	public void setDateCreation(Date dateCreation);

	@Override
	public Revue cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}