/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package offreemploi.model.impl;

import offreemploi.model.Offreemploi;

import offreemploi.service.OffreemploiLocalServiceUtil;

/**
 * The extended model base implementation for the Offreemploi service. Represents a row in the &quot;WAFABAIL_Offreemploi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OffreemploiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OffreemploiImpl
 * @see Offreemploi
 * @generated
 */
public abstract class OffreemploiBaseImpl
	extends OffreemploiModelImpl implements Offreemploi {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a offreemploi model instance should use the <code>Offreemploi</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			OffreemploiLocalServiceUtil.addOffreemploi(this);
		}
		else {
			OffreemploiLocalServiceUtil.updateOffreemploi(this);
		}
	}

}