/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package revue.model.impl;

import revue.model.Revue;

import revue.service.RevueLocalServiceUtil;

/**
 * The extended model base implementation for the Revue service. Represents a row in the &quot;WAFABAIL_Revue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RevueImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RevueImpl
 * @see Revue
 * @generated
 */
public abstract class RevueBaseImpl extends RevueModelImpl implements Revue {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a revue model instance should use the <code>Revue</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RevueLocalServiceUtil.addRevue(this);
		}
		else {
			RevueLocalServiceUtil.updateRevue(this);
		}
	}

}